version: '3.4'

services:
  catalogdb:
    image: postgres
    
  basketdb:
    image: postgres
    
  distributedcache:
    image: redis
    
  catalog.api:
    image: catalog.api
    container_name: Catalog.API
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      
  basket.api:
    image: basket.api
    container_name: Basket.API
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes: 
  postgres_catalog:
  postgres_basket:
